spring.application.name=lavanet-api

#====== PROPIEDADES DE LA DB ======
spring.datasource.url=${URL_DB}
spring.datasource.username=${USER_DB}
spring.datasource.password=${PASS_DB}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

#======= PROPIEDADES JWT =========
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000

#======== PROPUIEDADES PAR LOGS ===== 
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.lavanet=DEBUG

